In [1]:
import numpy as np

In [2]:
 my_array = np.array([0,1,2,3])

In [3]:
my_array

array([0, 1, 2, 3])

In [4]:
my_array.dtype

dtype('int32')

In [5]:
str_array = my_array.astype(str)

In [6]:
for i in my_array:
    print i*4

0
4
8
12


In [7]:
dim2_array = np.array([[0,1,2,3],[0,1,2,3],[0,1,2,4]])

In [8]:
dim2_array

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 4]])

In [9]:
dim2_array.ndim

2

In [11]:
dim2_array.shape

(3L, 4L)

In [12]:
dim2_array.size

12

In [14]:
np.mean(dim2_array)

1.5833333333333333

In [15]:
np.mean(dim2_array,axis=0)

array([ 0.        ,  1.        ,  2.        ,  3.33333333])

In [16]:
np.mean(dim2_array,axis=1)

array([ 1.5 ,  1.5 ,  1.75])

In [17]:
dim2_array[0]

array([0, 1, 2, 3])

In [19]:
dim2_array[:]

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 4]])

In [18]:
dim2_array[:2]

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [21]:
dim2_array[:2,:]

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [22]:
dim2_array[:2,:2]

array([[0, 1],
       [0, 1]])

In [25]:
dim2_array[:,:2]

array([[0, 1],
       [0, 1],
       [0, 1]])

In [23]:
dim2_array[0][::-1]

array([3, 2, 1, 0])

In [26]:
pwd

u'C:\\Users\\rahul.a.tripathi'

In [31]:
np.savetxt('lookatarray.csv',dim2_array, delimiter = ',')

In [33]:
np.genfromtxt('lookatarray.csv', delimiter = ',')

array([[  0.,   1.,   2.,   3.],
       [  0.,   1.,   2.,   3.],
       [  0.,   1.,   2.,  nan]])

In [34]:
np.nan

nan

In [35]:
?np.nan

In [36]:
??np.nan

In [37]:
arr = np.array([0,7,1,8, np.nan])

In [38]:
arr

array([  0.,   7.,   1.,   8.,  nan])

In [39]:
np.mean(arr)

nan

In [40]:
arr2 = np.ma.masked_array(arr, np.isnan(arr))

In [41]:
arr2

masked_array(data = [0.0 7.0 1.0 8.0 --],
             mask = [False False False False  True],
       fill_value = 1e+20)